# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/newbar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1600, 382)
        self.textEdit = QtWidgets.QPlainTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 1601, 128))
        self.textEdit.setObjectName("textEdit")
        self.fileLabel = QtWidgets.QLabel(Form)
        self.fileLabel.setGeometry(QtCore.QRect(1300, 128, 301, 256))
        self.fileLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.fileLabel.setWordWrap(True)
        self.fileLabel.setObjectName("fileLabel")
        self.previewLabel = QtWidgets.QLabel(Form)
        self.previewLabel.setGeometry(QtCore.QRect(16, 128, 256, 256))
        self.previewLabel.setText("")
        self.previewLabel.setObjectName("previewLabel")
        self.tabs = QtWidgets.QTabWidget(Form)
        self.tabs.setGeometry(QtCore.QRect(280, 128, 1010, 260))
        self.tabs.setStyleSheet("border: none;")
        self.tabs.setObjectName("tabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.searchResults = QtWidgets.QListWidget(self.tab)
        self.searchResults.setGeometry(QtCore.QRect(0, 0, 1000, 231))
        self.searchResults.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.searchResults.setObjectName("searchResults")
        self.tabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.bookmarks = QtWidgets.QListWidget(self.tab_2)
        self.bookmarks.setGeometry(QtCore.QRect(0, 0, 1000, 231))
        self.bookmarks.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.bookmarks.setObjectName("bookmarks")
        self.tabs.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.recentFiles = QtWidgets.QListWidget(self.tab_3)
        self.recentFiles.setEnabled(True)
        self.recentFiles.setGeometry(QtCore.QRect(0, 0, 1000, 231))
        self.recentFiles.setObjectName("recentFiles")
        self.tabs.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.relevantFiles = QtWidgets.QListWidget(self.tab_4)
        self.relevantFiles.setGeometry(QtCore.QRect(0, 0, 1000, 231))
        self.relevantFiles.setObjectName("relevantFiles")
        self.tabs.addTab(self.tab_4, "")
        self.tabs.raise_()
        self.textEdit.raise_()
        self.fileLabel.raise_()
        self.previewLabel.raise_()

        self.retranslateUi(Form)
        self.tabs.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.textEdit.setPlaceholderText(_translate("Form", "Search..."))
        self.fileLabel.setText(_translate("Form", "TextLabel"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab), _translate("Form", "Search Results"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_2), _translate("Form", "Bookmarks"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_3), _translate("Form", "Recent Files"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_4), _translate("Form", "Relevance"))
