# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/bar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1600, 382)
        self.textEdit = QtWidgets.QPlainTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 1601, 128))
        self.textEdit.setObjectName("textEdit")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(300, 128, 1000, 256))
        self.listWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.listWidget.setObjectName("listWidget")
        self.fileLabel = QtWidgets.QLabel(Form)
        self.fileLabel.setGeometry(QtCore.QRect(1300, 128, 301, 256))
        self.fileLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.fileLabel.setWordWrap(True)
        self.fileLabel.setObjectName("fileLabel")
        self.previewLabel = QtWidgets.QLabel(Form)
        self.previewLabel.setGeometry(QtCore.QRect(0, 128, 301, 256))
        self.previewLabel.setText("")
        self.previewLabel.setObjectName("previewLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.textEdit.setPlaceholderText(_translate("Form", "Search..."))
        self.fileLabel.setText(_translate("Form", "TextLabel"))
